defaults: &defaults
  working_directory: ~/DCSRoverScala
  docker:
      - image: openjdk:8
  environment:
    SBT_VERSION: 1.1.1

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
#      - run:
#          name: Get sbt binary
#          command: |
#            apt install -y curl
#            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
#            dpkg -i sbt-$SBT_VERSION.deb
#            rm sbt-$SBT_VERSION.deb

      - checkout

      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: gradle-cache

      - run:
          name: make gradlew executable
          command: chmod +x gradlew

      - run:
          name: Test
          command: ./gradlew test

      - save_cache:
          key: gradle-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.gradle"
            - "~/.m2"